version: "3.8"

services:
    ollama:
        image: ollama/ollama:latest
        ports:
            - 11434:11434
        volumes:
            - ollama:/ollama
        restart: unless-stopped

        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

volumes:
    ollama:
